### ISSUE TITLE
stuck on composer for 1hr+

### ISSUE THREAD

**Issue by Maskedman** [GR360RY/snipeit-ansible#14]
did something change in composer? it is now stuck for over 1hr+ at this step, when running it in the vagrant environment.

**Comment by GR360RY** [comment]
Nope, nothing is changed - I will look at it today.

**Comment by tknodell-rally** [comment]
+1

**Comment by GR360RY** [comment]
@Maskedman and @tknodell-rally,

composer.phar hitting the github api rate limit which drops you interactive shell and Ansible cannot handle it.  

@snipe - This probably should be fixed in upstream installation instruction as well:

Here is the link for the reference:
https://circleci.com/docs/composer-api-rate-limit

**Comment by snipe** [comment]
@GR360RY - I had actually tried `--prefer-source --no-interaction`, and it didn't seem to help. https://github.com/snipe/snipe-it/commit/c255edaf617872ac4a896106e56cc816209c2d5b
